### ISSUE TITLE
AllNicknames is throwing an exception

### ISSUE THREAD

**Issue by shadedblue** [shadedblue/CampingBot#27]
[1]
org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 235
	at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:171)
	at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:1)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:717)
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:47)
	at ca.hapke.campbinning.bot.CampingBotEngine.sendMsg(CampingBotEngine.java:315)
	at ca.hapke.campbinning.bot.CampingBotEngine.sendMsg(CampingBotEngine.java:306)
	at ca.hapke.campbinning.bot.commands.response.TextCommandResult.send(TextCommandResult.java:26)
	at ca.hapke.campbinning.bot.CampingBotEngine.onUpdateReceived(CampingBotEngine.java:285)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:306)

[2]

org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 231
	at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:171)
	at org.telegram.telegrambots.meta.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:1)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:717)
	at org.telegram.telegrambots.meta.bots.AbsSender.execute(AbsSender.java:47)
	at ca.hapke.campbinning.bot.CampingBotEngine.sendMsg(CampingBotEngine.java:315)
	at ca.hapke.campbinning.bot.CampingBotEngine.sendMsg(CampingBotEngine.java:306)
	at ca.hapke.campbinning.bot.commands.response.TextCommandResult.send(TextCommandResult.java:26)
	at ca.hapke.campbinning.bot.CampingBotEngine.onUpdateReceived(CampingBotEngine.java:285)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.telegram.telegrambots.meta.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:306)

**Comment by shadedblue** [comment]
Misused Markup character in a nickname:
https://core.telegram.org/bots/api#markdownv2-style
